# Generated by Django 5.2 on 2025-04-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=12)),
            ],
        ),
    ]
